"""Added telegram subscriber table

Revision ID: 3b1aa75227a8
Revises: 5191f599e905
Create Date: 2020-02-22 17:39:56.777690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1aa75227a8'
down_revision = '5191f599e905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_subscriber_chat_id'), 'telegram_subscriber', ['chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_subscriber_chat_id'), table_name='telegram_subscriber')
    op.drop_table('telegram_subscriber')
    # ### end Alembic commands ###
