"""updated trade volume column

Revision ID: 515891772c1e
Revises: e2e4b73f06f0
Create Date: 2020-04-20 23:07:20.375917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515891772c1e'
down_revision = 'e2e4b73f06f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('volume', sa.Integer(), nullable=True))
    op.drop_column('company', 'buy_vol')
    op.drop_column('company', 'sell_vol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('sell_vol', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('buy_vol', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('company', 'volume')
    # ### end Alembic commands ###
