"""Initial commit

Revision ID: 5191f599e905
Revises: 
Create Date: 2020-02-22 11:20:04.768062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5191f599e905'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=8), nullable=False),
    sa.Column('stock_name', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('company_site', sa.String(length=256), nullable=True),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_stock_code'), 'company', ['stock_code'], unique=True)
    op.create_index(op.f('ix_company_stock_name'), 'company', ['stock_name'], unique=False)
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('announced_date', sa.DateTime(), nullable=False),
    sa.Column('ann_id', sa.String(length=16), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ann_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement')
    op.drop_index(op.f('ix_company_stock_name'), table_name='company')
    op.drop_index(op.f('ix_company_stock_code'), table_name='company')
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
