"""dropping columns

Revision ID: 75689043583a
Revises: 15e594364238
Create Date: 2020-04-18 22:03:06.255693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75689043583a'
down_revision = '15e594364238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcement', 'announced_date')
    op.drop_column('company', 'last_update')
    op.drop_column('subscribe', 'last_sent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribe', sa.Column('last_sent', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('last_update', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('announcement', sa.Column('announced_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
