"""Added day traded high low

Revision ID: 77fe932d5743
Revises: 515891772c1e
Create Date: 2020-05-29 05:21:02.559896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77fe932d5743'
down_revision = '515891772c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('day_high', sa.Float(), nullable=True))
    op.add_column('company', sa.Column('day_low', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'day_low')
    op.drop_column('company', 'day_high')
    # ### end Alembic commands ###
