"""adding columns

Revision ID: 7e71742293d7
Revises: 75689043583a
Create Date: 2020-04-18 22:03:46.310210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e71742293d7'
down_revision = '75689043583a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('announced_date', sa.Date(), nullable=True))
    op.execute("UPDATE announcement SET announced_date = NOW()")
    op.alter_column('announcement', 'announced_date', nullable=False)
    op.add_column('company', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.execute("UPDATE company SET last_update = NOW()")
    op.alter_column('company', 'last_update', nullable=False)
    op.add_column('subscribe', sa.Column('last_sent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribe', 'last_sent')
    op.drop_column('company', 'last_update')
    op.drop_column('announcement', 'announced_date')
    # ### end Alembic commands ###
