"""updated telegram subscribers

Revision ID: d422004e26a5
Revises: 33e4eb51f705
Create Date: 2020-03-05 00:14:35.001755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd422004e26a5'
down_revision = '33e4eb51f705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegramsubscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('joined_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegramsubscriber_chat_id'), 'telegramsubscriber', ['chat_id'], unique=True)
    op.create_table('subscribe',
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['telegramsubscriber.id'], )
    )
    op.drop_index('ix_telegram_subscriber_chat_id', table_name='telegram_subscriber')
    op.drop_table('telegram_subscriber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_subscriber',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telegram_subscriber_chat_id', 'telegram_subscriber', ['chat_id'], unique=1)
    op.drop_table('subscribe')
    op.drop_index(op.f('ix_telegramsubscriber_chat_id'), table_name='telegramsubscriber')
    op.drop_table('telegramsubscriber')
    # ### end Alembic commands ###
